name: Compile to JS

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Scala to JS
      run: sbt fastOptJS
    - name: Stage changes
      run: git add .
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Reroll JS from Scala"
