name: Generate element and trigraph docs

on:
  push:

jobs:
  gen-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build jar
      run: sbt vyxalJVM/assembly
    - name: Update elements.txt and trigraphs.txt
      run: |
        java -jar jvm/target/scala-*/vyxal-*.jar --docs > documentation/elements.txt
        java -jar jvm/target/scala-*/vyxal-*.jar --sugar > documentation/trigraphs.txt
    - name: Stage changes
      run: git add .
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Refresh element and/or trigraph docs from recent commit"
