name: Generate element docs

on:
  push:

jobs:
  gen-element-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Create elements.txt and literate mappings
      run: |
        sbt vyxalJVM/assembly
        java -jar jvm/target/scala-*/vyxal-*.jar --docs > documentation/elements.txt
        java -jar jvm/target/scala-*/vyxal-*.jar --docsLiterate > shared/src/main/scala/LiterateMappings.scala
    - name: Stage changes
      run: git add .
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Refresh element documentation from recent commit"
