---
name: Create release from tag

on:
  push:
    tags:
      - "v3*"

# Names of the artifacts and executables for each platform
env:
  LINUX_NAME: vyxal-linux
  WINDOWS_NAME: vyxal-windows
  MACOS_NAME: vyxal-macos

jobs:
  native-exes:
    name: Generate executable for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            exe-name: ${{ env.LINUX_NAME }}
          - os: windows-latest
            exe-name: ${{ env.WINDOWS_NAME }}
          - os: macos-latest
            exe-name: ${{ env.MACOS_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build executable
        run: sbt vyxalNative/nativeLink
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - name: Name executable
        run: |
          mv native/target/scala-*/vyxal-out ${{ matrix.exe-name }}-${{ steps.tagName.outputs.tag }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.exe-name }}
          path: ${{ matrix.exe-name }}-*

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build jar
        run: sbt vyxalJVM/assembly

      - name: Make artifacts folder
        run: |
          mkdir artifacts
          mv jvm/target/scala-*/vyxal-*.jar artifacts/

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.LINUX_NAME }}
          path: artifacts/

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.WINDOWS_NAME }}
          path: artifacts/

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.MACOS_NAME }}
          path: artifacts/

      - name: Release 🚀
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/*
