name: Lint and format

on:
  push:
    paths-ignore:
      - 'documentation/**'
      - 'pages/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Run Scalafix and Scalafmt
      run: sbt vyxalJVM/scalafix vyxalJVM/scalafmt
    - name: Stage changes
      run: git add .
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Scalafix changes"
