name: Test and upload jar

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Test JVM
      run: sbt vyxalJVM/test
    - name: Test Native
      run: sbt vyxalNative/test
    - name: Build jar
      run: sbt vyxalJVM/assembly
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: jvm/target/scala-*/vyxal-*.jar
    - name: Create elements.txt
      run: java -jar jvm/target/scala-*/vyxal-*.jar --docs > documentation/elements.txt
    - name: Create literate mappings
      run: java -jar jvm/target/scala-*/vyxal-*.jar --docsLiterate > shared/src/main/scala/LiterateMappings.scala
    - name: Stage changes
      run: git add .
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Refresh element documentation from recent commit"
