name: Test and upload native executables

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Test Native
      run: sbt vyxalNative/test

  build:
    name: Build native executable on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test
    if: github.ref == 'refs/heads/${{ env.V3_MAIN }}'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build executable
      run: sbt vyxalNative/nativeLink
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vyxal-${{ matrix.os }}
        path: native/target/scala-*/vyxal-out
