name: Test JVM and Native

on:
  push:
    paths-ignore:
      - "documentation/**"
      - "js/**"
      - "pages/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Test JVM
        run: sbt vyxalJVM/test

      - name: Test Native
        run: sbt vyxalNative/test
