name: Test and upload jar

on:
  push:
  pull_request:

jobs:
  build:
    name: Test/build native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Test Native
      run: sbt vyxalNative/test

    - name: Build executable if on ${{ V3_MAIN }}
      if: github.ref == 'refs/heads/${{ V3_MAIN }}'
      run: sbt vyxalNative/nativeLink
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vyxal-native
        path: native/target/scala-*/vyxal-out
